version: "3.8"

services:

  nginx:
    image: nginx
    build:
      context: requirements/nginx/
    container_name: nginx
    restart: on-failure
    ports:
      - 443:443
    volumes:
      - WordPress:/var/www/html/
    networks:
      - uWu

  wordpress:
    image: wordpress
    build:
      context: requirements/wordpress/
    container_name: wordpress
    restart: on-failure
    ports:
      - 9000:9000
    volumes:
      - WordPress:/var/www/html/
    networks:
      - uWu

  mariadb:
    image: mariadb
    build:
      context: requirements/mariadb/
    container_name: mariadb
    restart: on-failure
    ports:
      - 3306:3306
    # volumes:
    #   - db:/etc
    networks:
      - uWu

networks:
  uWu:

volumes:
  WordPress:
    driver: local
    driver_opts:
      type: none
      device: /Users/iltafah/Desktop/Temp Volume/WordPress
      o: bind
  DB:
    driver: local
    driver_opts:
      type: none
      device: /Users/iltafah/Desktop/Temp Volume/DB
      o: bind