version: "3.8"

services:

  nginx:
    image: nginx
    build:
      context: requirements/nginx/
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - WordPress:/var/www/html/wordpress
    networks:
      - uWu

  wordpress:
    image: wordpress
    build:
      context: requirements/wordpress/
    container_name: wordpress
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - 9000:9000
    volumes:
      - WordPress:/var/www/html/wordpress
    networks:
      - uWu
    environment:
      DB_HOST: mariadb
      DB_NAME: wordpress
      DB_USER: ${SUPER_USER}
      DB_PASS: ${SUPER_USER_PASS}
      ADMIN_USER: ${SUPER_USER}
      ADMIN_PASS: ${SUPER_USER_PASS}
      AUTHOR_USER: ${SECONDRY_USER}
      AUTHOR_PASS: ${SECONDRY_USER_PASS}

  mariadb:
    image: mariadb
    build:
      context: requirements/mariadb/
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      # - /var/lib/mysql
      - DB:/var/lib/mysql
    networks:
      - uWu
    environment:
      DB_NAME: wordpress
      DB_USER: ${SUPER_USER}
      DB_PASS: ${SUPER_USER_PASS}
      DOCKER_NETWORK: ${DOCKER_COMPOSE_NETWORK_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 42s
      retries: 3

  redis:
    image: redis
    build:
      context: requirements/bonus/redis/
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - uWu

  ftp:
    image: ftp
    build:
      context: requirements/bonus/ftp/
      args:
        FTP_USER: ${SUPER_USER}
        FTP_USER_PASS: ${SUPER_USER_PASS}
    container_name: ftp
    restart: always
    ports:
      - 21:21
      - 41337:41337
    networks:
      - uWu

  adminer:
    image: adminer
    build:
      context: requirements/bonus/adminer/
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - uWu

  portainer:
    image: portainer
    build:
      context: requirements/bonus/portainer/
      args:
        ADMIN_PASS: ${PORTAINER_ADMIN_SUPER_PASS}
    container_name: portainer
    restart: always
    ports:
      - 4242:4242
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # docker context ls
    networks:
      - uWu

  static-site:
    image: static-site
    build:
      context: requirements/bonus/static-site/
    container_name: static-site
    restart: always
    ports:
      - 80:80
    networks:
      - uWu

networks:
  uWu:

volumes:
  WordPress:
    driver: local
    driver_opts:
      type: none
      device: ${WordPressVolumePath}
      o: bind
  DB:
    driver: local
    driver_opts:
      type: none
      device: ${MariaDbVolumePath}
      o: bind
