version: "3.8"

services:

  nginx:
    image: nginx
    build:
      context: requirements/nginx/
    container_name: nginx
    restart: on-failure
    ports:
      - 443:443
    volumes:
      - WordPress:/var/www/html/
    networks:
      - uWu

  wordpress:
    image: wordpress
    build:
      context: requirements/wordpress/
    container_name: wordpress
    restart: on-failure
    ports:
      - 9000:9000
    volumes:
      - WordPress:/var/www/html/
    networks:
      - uWu
    environment:
      DB_HOST: mariadb
      DB_NAME: wordpress
      DB_USER: ${SUPER_USER}
      DB_PASS: ${SUPER_USER_PASS}
      ADMIN_USER: ${SUPER_USER}
      ADMIN_PASS: ${SUPER_USER_PASS}
      AUTHOR_USER: ${SECONDRY_USER}
      AUTHOR_PASS: ${SECONDRY_USER_PASS}
        

  mariadb:
    image: mariadb
    build:
      context: requirements/mariadb/
    container_name: mariadb
    restart: on-failure
    ports:
      - 3306:3306
    # volumes:
    #   - db:/etc
    networks:
      - uWu
    environment:
      DB_NAME: wordpress
      DB_USER: ${SUPER_USER}
      DB_PASS: ${SUPER_USER_PASS}
      DOCKER_NETWORK: ${DOCKER_COMPOSE_NETWORK_NAME}

  redis:
    image: redis
    build:
      context: requirements/bonus/redis/
    container_name: redis
    restart: on-failure
    ports:
      - 6379:6379
    networks:
      - uWu

  ftp:
    image: ftp
    build:
      context: requirements/bonus/ftp/
    container_name: ftp
    restart: on-failure
    ports:
      - 21:21
      - 41337:41337
    networks:
      - uWu
    environment:
      FTP_USER: ${SUPER_USER}
      FTP_USER_PASS: ${SUPER_USER_PASS}

  adminer:
    image: adminer
    build:
      context: requirements/bonus/adminer/
    container_name: adminer
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - uWu

  portainer:
    image: portainer
    build:
      context: requirements/bonus/portainer/
    container_name: portainer
    restart: on-failure
    ports:
      - 4242:4242
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # docker context ls
      # - "portainer_data:/data"
    networks:
      - uWu
    environment:
      ADMIN_PASS: ${SUPER_USER_PASS}

  static-site:
    image: static-site
    build:
      context: requirements/bonus/static-site/
    container_name: static-site
    restart: on-failure
    ports:
      - 80:80
    networks:
      - uWu

networks:
  uWu:

volumes:
  WordPress:
    driver: local
    driver_opts:
      type: none
      device: /Users/iltafah/Desktop/Temp Volume/WordPress
      o: bind
  DB:
    driver: local
    driver_opts:
      type: none
      device: /Users/iltafah/Desktop/Temp Volume/DB
      o: bind
  # portainer_data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /Users/iltafah/Desktop/Temp Volume/Portainer
  #     o: bind
  